### ISSUE TITLE
Cannot install pypdfocr using pip3 : Syntaxerror in file

### ISSUE THREAD

**Issue by srdg** [virantha/pypdfocr#75]
I tried to install pypdfocr using `pip3` and this is the error log :
```
Collecting pypdfocr
  Downloading https://files.pythonhosted.org/packages/c3/23/1bf42cb12af63d498fcd425882815c21efef37800514dbad9fa28918df5e/pypdfocr-0.9.1.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 96kB/s 
Requirement already satisfied (use --upgrade to upgrade): pillow>=2.2 in /usr/local/lib/python3.5/dist-packages (from pypdfocr)
Requirement already satisfied (use --upgrade to upgrade): reportlab>=2.7 in /usr/lib/python3/dist-packages (from pypdfocr)
Collecting watchdog>=0.6.0 (from pypdfocr)
  Downloading https://files.pythonhosted.org/packages/54/7d/c7c0ad1e32b9f132075967fc353a244eb2b375a3d2f5b0ce612fd96e107e/watchdog-0.8.3.tar.gz (83kB)
    100% |████████████████████████████████| 92kB 296kB/s 
Collecting pypdf2>=1.23 (from pypdfocr)
  Downloading https://files.pythonhosted.org/packages/b4/01/68fcc0d43daf4c6bdbc6b33cc3f77bda531c86b174cac56ef0ffdb96faab/PyPDF2-1.26.0.tar.gz (77kB)
    100% |████████████████████████████████| 81kB 512kB/s 
Collecting evernote (from pypdfocr)
  Downloading https://files.pythonhosted.org/packages/f9/6b/877f8edef8ef040d32eb38f3bf6322ba334de9d10614d8db9d869c162fc1/evernote-1.25.3.tar.gz (141kB)
    100% |████████████████████████████████| 143kB 403kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-z9qh7cxz/evernote/setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'

```
Is this because `setup.py` is written in `Python 2.x`? Is there a bundle available for `Python3` as well?

**Comment by jamesbroadhead** [comment]
This is resolved in #71, which adds python3 support

**Comment by bruno-robert** [comment]
I'm still getting the same error when installing with pip3

**Comment by srdg** [comment]
I got a notification and retried installing, the error still persists.
Here is the error log : 
```
 ~ $ pip3 install pypdfocr
Collecting pypdfocr
  Downloading https://files.pythonhosted.org/packages/c3/23/1bf42cb12af63d498fcd425882815c21efef37800514dbad9fa28918df5e/pypdfocr-0.9.1.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 133kB/s 
Collecting pillow>=2.2 (from pypdfocr)
  Downloading https://files.pythonhosted.org/packages/de/62/6358ccd27b9e340affaa29e3e678b5d93a4b17f6bd7533fd6e6e87930b12/Pillow-6.0.0-cp35-cp35m-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 277kB/s 
Collecting reportlab>=2.7 (from pypdfocr)
  Downloading https://files.pythonhosted.org/packages/a0/36/10777156a30160bade690368488d86f331e0e70c1b56ea6091761f54d6a1/reportlab-3.5.20-cp35-cp35m-manylinux1_x86_64.whl (2.6MB)
    100% |████████████████████████████████| 2.6MB 149kB/s 
Collecting watchdog>=0.6.0 (from pypdfocr)
  Downloading https://files.pythonhosted.org/packages/bb/e3/5a55d48a29300160779f0a0d2776d17c1b762a2039b36de528b093b87d5b/watchdog-0.9.0.tar.gz (85kB)
    100% |████████████████████████████████| 92kB 964kB/s 
Collecting pypdf2>=1.23 (from pypdfocr)
  Downloading https://files.pythonhosted.org/packages/b4/01/68fcc0d43daf4c6bdbc6b33cc3f77bda531c86b174cac56ef0ffdb96faab/PyPDF2-1.26.0.tar.gz (77kB)
    100% |████████████████████████████████| 81kB 1.4MB/s 
Collecting evernote (from pypdfocr)
  Downloading https://files.pythonhosted.org/packages/f9/6b/877f8edef8ef040d32eb38f3bf6322ba334de9d10614d8db9d869c162fc1/evernote-1.25.3.tar.gz (141kB)
    100% |████████████████████████████████| 143kB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-51vzefgf/evernote/setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-51vzefgf/evernote/
You are using pip version 8.1.1, however version 19.1 is available.
```

**Comment by tweinreich** [comment]
I experienced this error as well (_Python 3.7.2 and pip 19.1.1_). With pip2 it works as expected.

**Comment by kebanks** [comment]
I'm experiencing the same error even with pip2

**Comment by jainal09** [comment]
I prefer Using this library its more advanced and has more features.
https://github.com/jbarlow83/OCRmyPDF
